[book]
title = "EASYDATACenter & EASYSYSTEMBuilder Full Developer Documentations"
description = "All Development information, Shared Parts, and more other are Published"
authors = ["Libor Svoboda"]
language = "en"
src = "."
multilingual = false

[rust]
edition = "2018"

[output.html]
default-theme = "rust"
mathjax-support = true
site-url = "/mdBook/"
git-repository-url = "https://github.com/liborsvoboda/EASYSYSTEM-EASYSERVER-EN"
edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

#use cms preprocessor
[preprocessor.cms]
# meta/first-line/filename
title = "meta"

[output.html.fold]
enable = true
level = 0

[build]
create-missing = false

#use as mdbook preprocessor
#[preprocessor.auto-gen-summary]
#first-line-as-link-text = true # indicate mdbook to make the first line(default the file name) of markdown file as the link text in SUMMARY.md
