
--BACKUP
USE[SHOPINGER]
DROP USER [shopinger];
DBCC SHRINKFILE (SHOPINGER_log, 1);
BACKUP DATABASE [SHOPINGER] TO DISK = N'C:\Database\SHOPINGER.bak'
DBCC SHRINKFILE (SHOPINGER_log, 1);
BACKUP DATABASE [SHOPINGER] TO DISK = N'C:\Database\SHOPINGER.bak'
GO

USE [SHOPINGER]
BEGIN TRY CREATE USER [shopinger] FOR LOGIN [shopinger] END TRY BEGIN CATCH END CATCH;
BEGIN TRY ALTER ROLE [db_datareader] ADD MEMBER [shopinger]; END TRY BEGIN CATCH END CATCH;


--RESTORE TO NEW FILES
ALTER DATABASE [SHOPINGER] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [SHOPINGER] FROM DISK = N'C:\Database\SHOPINGER.bak' 
WITH MOVE N'SHOPINGER' TO N'C:\Database\SHOPINGER.mdf',  
     MOVE N'SHOPINGER_log' TO N'C:\Database\SHOPINGER_log.ldf', FILE = 2,
RECOVERY,  REPLACE,  STATS = 10;
ALTER DATABASE [SHOPINGER] SET MULTI_USER;
