REM sqlcmd -U username -P password -S .\SQLEXPRESS -Q "ALTER DATABASE [GLOBALNET] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;RESTORE DATABASE [GLOBALNET] FROM DISK = N'C:\Database\DEFAULT_DATABASES\GLOBALNET.bak' WITH MOVE N'GLOBALNET' TO N'C:\Database\GLOBALNET.mdf',  MOVE N'GLOBALNET_log' TO N'C:\Database\GLOBALNET_log.ldf', FILE = 2,RECOVERY,  REPLACE,  STATS = 10;ALTER DATABASE [GLOBALNET] SET MULTI_USER;"
REM sqlcmd -U username -P password -S .\SQLEXPRESS -d GLOBALNET -Q "EXEC DB_SETRIGHTS"

sqlcmd -U username -P password -S .\SQLEXPRESS -Q "ALTER DATABASE [LICENSESRV] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;RESTORE DATABASE [LICENSESRV] FROM DISK = N'C:\Database\DEFAULT_DATABASES\LICENSESRV.bak' WITH MOVE N'LICENSESRV' TO N'C:\Database\LICENSESRV.mdf',  MOVE N'LICENSESRV_log' TO N'C:\Database\LICENSESRV_log.ldf', FILE = 2,RECOVERY,  REPLACE,  STATS = 10;ALTER DATABASE [LICENSESRV] SET MULTI_USER;"
sqlcmd -U username -P password -S .\SQLEXPRESS -d LICENSESRV -Q "EXEC DB_SETRIGHTS"

sqlcmd -U username -P password -S .\SQLEXPRESS -Q "ALTER DATABASE [PRUVODKY] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;RESTORE DATABASE [PRUVODKY] FROM DISK = N'C:\Database\DEFAULT_DATABASES\PRUVODKY.bak' WITH MOVE N'PRUVODKY' TO N'C:\Database\PRUVODKY.mdf',  MOVE N'PRUVODKY_log' TO N'C:\Database\PRUVODKY_log.ldf', FILE = 2,RECOVERY,  REPLACE,  STATS = 10;ALTER DATABASE [PRUVODKY] SET MULTI_USER;"
sqlcmd -U username -P password -S .\SQLEXPRESS -d PRUVODKY -Q "EXEC DB_SETRIGHTS"

sqlcmd -U username -P password -S .\SQLEXPRESS -Q "ALTER DATABASE [SHOPINGER] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;RESTORE DATABASE [SHOPINGER] FROM DISK = N'C:\Database\DEFAULT_DATABASES\SHOPINGER.bak' WITH MOVE N'SHOPINGER' TO N'C:\Database\SHOPINGER.mdf',  MOVE N'SHOPINGER_log' TO N'C:\Database\SHOPINGER_log.ldf', FILE = 2,RECOVERY,  REPLACE,  STATS = 10;ALTER DATABASE [SHOPINGER] SET MULTI_USER;"
sqlcmd -U username -P password -S .\SQLEXPRESS -d SHOPINGER -Q "EXEC DB_SETRIGHTS"

sqlcmd -U username -P password -S .\SQLEXPRESS -Q "ALTER DATABASE [LICENSESHOPER] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;RESTORE DATABASE [LICENSESHOPER] FROM DISK = N'C:\Database\DEFAULT_DATABASES\LICENSESHOPER.bak' WITH MOVE N'LICENSESHOPER' TO N'C:\Database\LICENSESHOPER.mdf',  MOVE N'LICENSESHOPER_log' TO N'C:\Database\LICENSESHOPER_log.ldf', FILE = 2,RECOVERY,  REPLACE,  STATS = 10;ALTER DATABASE [LICENSESHOPER] SET MULTI_USER;"
sqlcmd -U username -P password -S .\SQLEXPRESS -d LICENSESHOPER -Q "EXEC DB_SETRIGHTS"

sqlcmd -U username -P password -S .\SQLEXPRESS -Q "ALTER DATABASE [EASYBUILDER] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;RESTORE DATABASE [EASYBUILDER] FROM DISK = N'C:\Database\DEFAULT_DATABASES\EASYBUILDER.bak' WITH MOVE N'EASYBUILDER' TO N'C:\Database\EASYBUILDER.mdf',  MOVE N'EASYBUILDER_log' TO N'C:\Database\EASYBUILDER_log.ldf', FILE = 2,RECOVERY,  REPLACE,  STATS = 10;ALTER DATABASE [EASYBUILDER] SET MULTI_USER;"
sqlcmd -U username -P password -S .\SQLEXPRESS -d EASYBUILDER -Q "EXEC DB_SETRIGHTS"
