using System;

/**
 * !!! System Class Definitions
 * All Class Types which you need for create Any system
 * 
 * Simple COPY/PASTE using
 * ONLY Replace 'TemplateClassList' and DataFields [DATASET] with your Table Name
 *
*/

namespace GlobalNET.Classes {

    /// <summary>
    /// Typical Table schema for API which you copy from Generated Model in API Server
    /// On API server is Automatically generated by Scaffold command
    /// Class is Same as API result
    /// Example Load Data: listVariable = await ApiCommunication.GetApiRequest<List<TemplateClassList>>(ApiUrls.TemplateClassList, null, App.UserData.Authentification.Token);
    /// </summary>
    public partial class ExampleClassList {
        public int Id { get; set; } = 0;
        public string SystemName { get; set; } = null;
        public string Description { get; set; } = null;
        public int UserId { get; set; }
        public bool Active { get; set; }
        public DateTime TimeStamp { get; set; }
    }

    /// <summary>
    /// Extend API Class with Custom Column in One dataset
    /// !!!SYSTEM CONDITION: Name must contain "Extended" 
    /// !!!FOR NULL SET IN THE JOING FIELDS BEFORE SEND OVER API
    /// 
    /// Move the fields with SAME NAME as Joined Table on API to ExtendedClass
    /// Will be set to 'null' Before API send
    /// 
    /// Using: for Translation, Info about joined table, etc
    /// It must be cleaned by operation "NullSetInExtensionFields" before Database operation 
    /// for disable join control on API for valid independent table
    /// Other is valid join key for other Tables
    /// </summary>
    public partial class ExtendedExampleClassList : TemplateClassList {

        public string Currency { get; set; }  // its join to table Currency
        public string TotalCurrency { get; set; }


        public ExtendedExampleClassList() { }
        public ExtendedExampleClassList(ItemList ch) {
            foreach (var prop in ch.GetType().GetProperties())
            { this.GetType().GetProperty(prop.Name).SetValue(this, prop.GetValue(ch, null), null); }
        }
    }


    /// <summary>
    /// WARNING: If you Add the field with Same Name as joined table in Database Model
    /// you must set this field as 'null' before send Insert / Update
    /// in HttpContent must Be as 'null' value other is taken as Data Join by API Server
    ///
    /// SIMPLE USING
    /// API Class is extended on root level by custom fields
    /// Example Load Data and Fill custom Fields:
    ///
    /// listVariable = await ApiCommunication.GetApiRequest<List<TemplateClassList>>(ApiUrls.TemplateClassList, null, App.UserData.Authentification.Token);
    /// listVariable.ForEach(async rec => { rec.Translation = await DBOperations.DBTranslation(rec.SystemName); });
    /// </summary>
    public partial class ExampleClassListWithLocalTranslation {
        public int Id { get; set; } = 0;
        public string SystemName { get; set; } = null;
        public string Description { get; set; } = null;
        public int UserId { get; set; }
        public bool Active { get; set; }
        public DateTime TimeStamp { get; set; }

        public string Translation { get; set; } = null;
    }


}